# -*- coding: utf-8 -*-
"""week3_Yashika_Aggarwal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gU3lmG3sRYoXoxlJ1ByVK0wDzz-nEK7
"""

# Install required libraries

!pip install xgboost -q

""" Import required libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

"""Upload and load the dataset

"""

df = pd.read_csv("Country-data.csv")

print("Dataset Shape:", df.shape)
df.head()

"""Clean dataset and handle missing values"""

df.columns = df.columns.str.strip()

df = df.drop_duplicates()

for col in df.columns:
    if col != "country":
        df[col] = pd.to_numeric(df[col], errors="coerce")

for col in df.columns:
    if col != "country":
        df[col] = df[col].fillna(df[col].median())

print(df.isnull().sum())

""" Separate features and scale the data"""

countries = df["country"]

X = df.drop("country", axis=1)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled.shape)

"""Find optimal clusters using Elbow Method"""

inertia = []

k_values = range(2, 11)

for k in k_values:
    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    km.fit(X_scaled)

    inertia.append(km.inertia_)

plt.figure(figsize=(8,5))
plt.plot(k_values, inertia, marker="o")
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.grid(True)
plt.show()

"""Train K-Means clustering model"""

best_k = 3

kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

kmeans_labels = kmeans.fit_predict(X_scaled)

df["KMeans_Cluster"] = kmeans_labels

df["KMeans_Cluster"].value_counts()

"""Evaluate clustering using Silhouette Score"""

score = silhouette_score(
    X_scaled,
    kmeans_labels
)

print("Silhouette Score:", round(score, 4))

"""Build DBSCAN clustering model"""

dbscan = DBSCAN(
    eps=1.5,
    min_samples=5
)

dbscan_labels = dbscan.fit_predict(X_scaled)

df["DBSCAN_Cluster"] = dbscan_labels

df["DBSCAN_Cluster"].value_counts()

"""Reduce dimensions using PCA"""

pca = PCA(n_components=2)

pca_features = pca.fit_transform(X_scaled)

df["PCA1"] = pca_features[:, 0]
df["PCA2"] = pca_features[:, 1]

df[["PCA1", "PCA2"]].head()

"""Visualize K-Means clusters in two dimensions"""

plt.figure(figsize=(10,6))

sns.scatterplot(
    x="PCA1",
    y="PCA2",
    hue="KMeans_Cluster",
    palette="viridis",
    data=df,
    s=100
)

plt.title("Country Segments using PCA and K-Means")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

"""Create target labels from K-Means clusters"""

y = kmeans_labels

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

""" Train Random Forest classifier"""

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_accuracy = accuracy_score(
    y_test,
    rf_pred
)

print("Random Forest Accuracy:", rf_accuracy)

"""Train XGBoost classifier"""

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.1,
    objective="multi:softprob",
    eval_metric="mlogloss",
    random_state=42
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)

xgb_accuracy = accuracy_score(
    y_test,
    xgb_pred
)

print("XGBoost Accuracy:", xgb_accuracy)

"""Identify important features using Random Forest"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(10)

"""Visualize top important features"""

plt.figure(figsize=(8,5))

sns.barplot(
    data=importance.head(10),
    x="Importance",
    y="Feature"
)

plt.title("Top Features Influencing Country Segmentation")
plt.show()

"""Generate cluster-wise socio-economic summary

"""

cluster_summary = df.groupby(
    "KMeans_Cluster"
)[X.columns].mean()

cluster_summary

"""# Section 14: Socio-Economic Observations

1. K-Means clustering successfully divided countries into three distinct groups based on socio-economic and health indicators.

2. One cluster contained highly developed countries characterized by high income levels, low child mortality, and high life expectancy.

3. Another cluster represented developing nations with moderate economic performance and improving health indicators.

4. The least developed cluster showed lower income levels, higher child mortality rates, and reduced life expectancy, indicating greater developmental challenges.

5. The clustering results reveal significant disparities in economic growth, healthcare quality, and living standards across countries, providing valuable insights for policy planning and resource allocation.

# Conclusion

* Successfully preprocessed and analyzed the country dataset using machine learning techniques.
* Applied K-Means and DBSCAN to identify meaningful country segments based on socio-economic indicators.
* Used PCA to visualize high-dimensional data and clearly distinguish country groups.
* Evaluated clustering quality using the Silhouette Score, confirming effective cluster formation.
* Trained Random Forest and XGBoost models to predict cluster membership with high accuracy.
* XGBoost achieved the best classification performance, while K-Means provided the most interpretable clustering results.
* The project demonstrated how data-driven approaches can support country development analysis and strategic decision-making.
"""